### ISSUE TITLE
hi :)

### ISSUE THREAD

**Issue by nelzon897** [zachjhuang/chaos-script#1]
Hi, I have a problem and I hope you can help me with it :). 
The problem is that the bot when launched gets to the character choice stage, then realizes that the right character is already connected and then starts spamming “city loaded” without anything else happening. Any ideas? Thanks

**Comment by zachjhuang** [comment]
If you're only starting the script with the --endless flag, then the issue should be fixed with the latest commit, just pull and rerun.
